INSERT INTO `APICommands` (`id`, `API`, `text`, `coreCommandId`, `priority`)
VALUES	( 1, 'TelegramAPI', '/start'				,  1, 0),
		( 2, 'TelegramAPI', 'Зарегистрироваться'	,  1, 0),
		( 3, 'TelegramAPI', '/add_show'				,  2, 0),
		( 4, 'TelegramAPI', 'Добавь'				,  2, 0),
		( 5, 'TelegramAPI', 'Добавь сериал'			,  2, 0),
		( 6, 'TelegramAPI', 'Подписаться на сериал'	,  2, 0),
		( 7, 'TelegramAPI', '/remove_show'			,  3, 0),
		( 8, 'TelegramAPI', 'Удали'					,  3, 0),
		( 9, 'TelegramAPI', 'Удали сериал'			,  3, 0),
		(10, 'TelegramAPI', 'Отписаться от сериала'	,  3, 0),
		(11, 'TelegramAPI', '/get_my_shows'			,  4, 0),
		(12, 'TelegramAPI', 'Мои сериалы'			,  4, 0),
		(13, 'TelegramAPI', '/mute'					,  5, 0),
		(14, 'TelegramAPI', 'Выключи уведомления'	,  5, 0),
		(15, 'TelegramAPI', '/cancel'				,  6, 0),
		(16, 'TelegramAPI', 'Отмена'				,  6, 0),
		(17, 'TelegramAPI', '/help'					,  7, 0),
		(18, 'TelegramAPI', 'Помощь'				,  7, 0),
		(19, 'TelegramAPI', 'Инфо'					,  7, 0),
		(20, 'TelegramAPI', 'Команды'				,  7, 0),
		(21, 'TelegramAPI', '/stop'					,  8, 0),
		(22, 'TelegramAPI', 'Стоп'					,  8, 0),
		(23, 'TelegramAPI', 'Удалиться'				,  8, 0),
		(24, 'TelegramAPI', '/share'				,  9, 0),
		(25, 'TelegramAPI', 'Поделиться'			,  9, 0),
		(26, 'TelegramAPI', 'Поделиться ботом'		,  9, 0),
		(27, 'TelegramAPI', '/donate'				, 10, 0),
		(28, 'TelegramAPI', 'Донат'					, 10, 0),
		(29, 'TelegramAPI', 'Задонатить'			, 10, 0),
		(30, 'TelegramAPI', '/broadcast'			, 11, 0),
		(31,       'VKAPI', '/start'				,  1, 0),
		(32,       'VKAPI', 'Старт'					,  1, 0),
		(33,       'VKAPI', 'Привет'				,  1, 0),
		(34,       'VKAPI', '/add_show'				,  2, 0),
		(35,       'VKAPI', 'Добавь'				,  2, 0),
		(36,       'VKAPI', 'Добавь сериал'			,  2, 0),
		(37,       'VKAPI', '/remove_show'			,  3, 0),
		(38,       'VKAPI', 'Удали'					,  3, 0),
		(39,       'VKAPI', 'Удали сериал'			,  3, 0),
		(40,       'VKAPI', '/get_my_shows'			,  4, 0),
		(41,       'VKAPI', 'Мои сериалы'			,  4, 0),
		(42,       'VKAPI', '/mute'					,  5, 0),
		(43,       'VKAPI', 'Выключи уведомления'	,  5, 0),
		(44,       'VKAPI', '/cancel'				,  6, 0),
		(45,       'VKAPI', 'Отмена'				,  6, 0),
		(46,       'VKAPI', '/help'					,  7, 0),
		(47,       'VKAPI', 'Помощь'				,  7, 0),
		(48,       'VKAPI', 'Команды'				,  7, 0),
		(49,       'VKAPI', '/stop'					,  8, 0),
		(50,       'VKAPI', 'Удалиться'				,  8, 0),
		(51,       'VKAPI', 'Удали меня'			,  8, 0),
		(52,       'VKAPI', '/share'				,  9, 0),
		(53,       'VKAPI', 'Поделиться ботом'		,  9, 0),
		(54,       'VKAPI', 'Поделиться'			,  9, 0),
		(55,       'VKAPI', '/donate'				, 10, 0),
		(56,       'VKAPI', 'Донат'					, 10, 0),
		(57,    'ViberAPI', 'Подписаться на сериал'	,  2, 0),
		(58,    'ViberAPI', 'Отписаться от сериала'	,  3, 0),
		(59,    'ViberAPI', 'Мои сериалы'			,  4, 0),
		(60,    'ViberAPI', 'Выключить уведомления'	,  5, 0),
		(61,    'ViberAPI', 'Отмена'				,  6, 0),
		(62,    'ViberAPI', 'Инфо'					,  7, 0),
		(63,    'ViberAPI', 'Помощь'				,  7, 0),
		(64,    'ViberAPI', 'Справка'				,  7, 0),
		(65,    'ViberAPI', 'Отписаться от бота'	,  8, 0),
		(66,    'ViberAPI', 'Поделиться ботом'		,  9, 0),
		(67,    'ViberAPI', 'Задонатить'			, 10, 0),
		(68,    'ViberAPI', 'Донат'					, 10, 0);
