CREATE TABLE `ShowTitleIndexVersions`(
	`id`		INT(10) UNSIGNED	NOT NULL AUTO_INCREMENT,
	`createdAt`	DATETIME 			NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`gramSize`	TINYINT UNSIGNED	NOT NULL,

	PRIMARY KEY (`id`)
);

