CREATE TABLE IF NOT EXISTS `APICommands` (
	`id`	INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`API`	VARCHAR(255) CHARACTER SET 'ascii' COLLATE 'ascii_bin' NOT NULL,
	`text`	VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
	`coreCommandId`	INT UNSIGNED NOT NULL,
	`priority`		INT UNSIGNED NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `API-Command` (`text` ASC, `API` ASC)
);

ALTER TABLE `APICommands`
	ADD CONSTRAINT `APICommands-FK-APIs`
		FOREIGN KEY (`API`)
		REFERENCES `APIs` (`name`)
		ON DELETE RESTRICT
		ON UPDATE CASCADE,

	ADD CONSTRAINT `APICommands-FK-coreCommands`
		FOREIGN KEY (`coreCommandId`)
		REFERENCES `coreCommands` (`id`)
		ON DELETE CASCADE
		ON UPDATE CASCADE;

